/* ============================================================
   Comprehensive Human Osteology Database
   Compiled from standard gross-anatomy references (Gray's Anatomy,
   Moore's Clinically Oriented Anatomy, Marieb's Human Anatomy &
   Physiology). Covers axial + appendicular skeleton with named
   bone markings: processes, fossae, foramina, sutures, condyles,
   tubercles, crests, notches, canals, fissures, sinuses, facets.
   ============================================================ */

const BONE_TYPES = {
  process:   { label: "Process",        color: "#7dd3fc" },
  fossa:     { label: "Fossa/Depression", color: "#c4b5fd" },
  foramen:   { label: "Foramen/Canal",   color: "#fca5a5" },
  suture:    { label: "Suture/Joint",    color: "#fcd34d" },
  tuberosity:{ label: "Tubercle/Tuberosity", color: "#86efac" },
  condyle:   { label: "Condyle/Facet",   color: "#f9a8d4" },
  crest:     { label: "Crest/Line",      color: "#fdba74" },
  notch:     { label: "Notch/Fissure",   color: "#a5b4fc" },
  region:    { label: "Region/Part",     color: "#d4d4d8" },
};

const BONES = [
/* ================= SKULL — CRANIAL BONES ================= */
{
  id: "frontal", name: "Frontal Bone", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Forms the forehead, roofs of the orbits, and most of the anterior cranial fossa.",
  parts: [
    { name: "Frontal Squama", type: "region", desc: "The vertical, plate-like portion forming the forehead." },
    { name: "Glabella", type: "region", desc: "Smooth, slightly raised area between the eyebrows, above the nose." },
    { name: "Superciliary Arches", type: "crest", desc: "Ridges above each orbit, deep to the eyebrows." },
    { name: "Supraorbital Margin", type: "region", desc: "The rounded upper rim of the orbit." },
    { name: "Supraorbital Foramen (Notch)", type: "foramen", desc: "Opening in the supraorbital margin for the supraorbital nerve and vessels." },
    { name: "Frontal Sinuses", type: "region", desc: "Paired mucosa-lined cavities within the bone above the nasal cavity." },
    { name: "Frontal Eminences (Tubers)", type: "tuberosity", desc: "Rounded prominences above each superciliary arch, more prominent in children." },
    { name: "Zygomatic Process", type: "process", desc: "Lateral projection that articulates with the zygomatic bone." },
    { name: "Temporal Lines (Sup./Inf.)", type: "crest", desc: "Curved ridges marking the origin of the temporalis muscle." },
    { name: "Orbital Plates", type: "region", desc: "Thin plates forming most of the roof of each orbit." },
  ],
},
{
  id: "parietal", name: "Parietal Bone (paired)", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Paired bones forming the superior and lateral walls of the cranial vault.",
  parts: [
    { name: "Sagittal Border", type: "region", desc: "Medial edge that meets its partner at the sagittal suture." },
    { name: "Squamous Border", type: "region", desc: "Inferior edge that overlaps the temporal bone (squamous suture)." },
    { name: "Frontal (Coronal) Border", type: "region", desc: "Anterior edge meeting the frontal bone at the coronal suture." },
    { name: "Occipital (Lambdoid) Border", type: "region", desc: "Posterior edge meeting the occipital bone at the lambdoid suture." },
    { name: "Parietal Eminence (Tuber)", type: "tuberosity", desc: "Bulge marking the point of earliest ossification." },
    { name: "Superior/Inferior Temporal Lines", type: "crest", desc: "Curved lines for attachment of temporal fascia and temporalis muscle." },
  ],
},
{
  id: "temporal", name: "Temporal Bone (paired)", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Houses the organs of hearing/balance; forms part of the cranial base and side wall.",
  parts: [
    { name: "Squamous Part", type: "region", desc: "Thin, flat, fan-shaped superior portion." },
    { name: "Zygomatic Process", type: "process", desc: "Bridges anteriorly to join the zygomatic bone, forming the zygomatic arch." },
    { name: "Mandibular Fossa", type: "fossa", desc: "Depression that articulates with the mandibular condyle (TMJ)." },
    { name: "Articular Tubercle", type: "tuberosity", desc: "Ridge anterior to the mandibular fossa; part of the TMJ." },
    { name: "External Acoustic Meatus", type: "foramen", desc: "Canal leading to the tympanic membrane." },
    { name: "Mastoid Process", type: "process", desc: "Rounded projection behind the ear; attachment for neck muscles." },
    { name: "Mastoid Notch", type: "notch", desc: "Groove medial to the mastoid process for the digastric muscle." },
    { name: "Styloid Process", type: "process", desc: "Slender, pointed spike projecting inferiorly; muscle/ligament attachment." },
    { name: "Stylomastoid Foramen", type: "foramen", desc: "Opening between styloid and mastoid processes; facial nerve (CN VII) exit." },
    { name: "Petrous Part", type: "region", desc: "Dense, pyramid-shaped portion housing the inner ear." },
    { name: "Internal Acoustic Meatus", type: "foramen", desc: "Canal for CN VII and CN VIII." },
    { name: "Jugular Fossa", type: "fossa", desc: "Depression housing the origin of the internal jugular vein." },
    { name: "Carotid Canal", type: "foramen", desc: "Passage for the internal carotid artery." },
    { name: "Tympanic Part", type: "region", desc: "Curved plate forming most of the wall of the external acoustic meatus." },
    { name: "Squamotympanic Fissure", type: "notch", desc: "Fissure between squamous and tympanic parts." },
  ],
},
{
  id: "occipital", name: "Occipital Bone", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Forms the posterior and inferior cranium, surrounding the foramen magnum.",
  parts: [
    { name: "Foramen Magnum", type: "foramen", desc: "Large opening for passage of the spinal cord/brainstem." },
    { name: "Occipital Condyles", type: "condyle", desc: "Oval processes that articulate with the atlas (C1)." },
    { name: "Hypoglossal Canal", type: "foramen", desc: "Passage for the hypoglossal nerve (CN XII), superior to each condyle." },
    { name: "External Occipital Protuberance", type: "tuberosity", desc: "Midline bump palpable at the back of the skull (ligamentum nuchae attachment)." },
    { name: "External Occipital Crest", type: "crest", desc: "Ridge running from the protuberance to the foramen magnum." },
    { name: "Superior Nuchal Line", type: "crest", desc: "Ridge marking attachment of trapezius/sternocleidomastoid." },
    { name: "Inferior Nuchal Line", type: "crest", desc: "Lower ridge for attachment of deep neck muscles." },
    { name: "Condylar Canal", type: "foramen", desc: "Posterior to each occipital condyle; transmits an emissary vein (variable)." },
    { name: "Jugular Notch", type: "notch", desc: "Notch that combines with temporal bone to form the jugular foramen." },
    { name: "Basilar Part (Basiocciput)", type: "region", desc: "Thick portion anterior to the foramen magnum, fusing with the sphenoid." },
  ],
},
{
  id: "sphenoid", name: "Sphenoid Bone", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Butterfly-shaped bone forming much of the central cranial base; articulates with nearly every other skull bone.",
  parts: [
    { name: "Body", type: "region", desc: "Central cube-shaped portion containing the sphenoidal sinuses." },
    { name: "Sella Turcica", type: "fossa", desc: "Saddle-shaped depression housing the pituitary gland (hypophyseal fossa)." },
    { name: "Dorsum Sellae", type: "region", desc: "Posterior wall of the sella turcica." },
    { name: "Anterior Clinoid Processes", type: "process", desc: "Bony projections from the lesser wings framing the sella turcica." },
    { name: "Posterior Clinoid Processes", type: "process", desc: "Projections from the dorsum sellae." },
    { name: "Greater Wings", type: "region", desc: "Large lateral extensions forming part of the middle cranial fossa and orbit." },
    { name: "Lesser Wings", type: "region", desc: "Smaller, anterior wing-like projections forming the posterior orbital roof." },
    { name: "Optic Canal", type: "foramen", desc: "Transmits the optic nerve (CN II) and ophthalmic artery." },
    { name: "Superior Orbital Fissure", type: "notch", desc: "Gap between greater and lesser wings; CN III, IV, VI and ophthalmic branch of V pass through." },
    { name: "Foramen Rotundum", type: "foramen", desc: "Transmits the maxillary branch of the trigeminal nerve (CN V2)." },
    { name: "Foramen Ovale", type: "foramen", desc: "Transmits the mandibular branch of the trigeminal nerve (CN V3)." },
    { name: "Foramen Spinosum", type: "foramen", desc: "Transmits the middle meningeal artery." },
    { name: "Pterygoid Processes", type: "process", desc: "Paired inferior projections, each with medial and lateral plates, for jaw-muscle attachment." },
    { name: "Pterygoid Hamulus", type: "process", desc: "Small hook-like process at the base of the medial pterygoid plate." },
  ],
},
{
  id: "ethmoid", name: "Ethmoid Bone", region: "Axial Skeleton", group: "Skull – Cranial Bones",
  blurb: "Light, spongy bone between the orbits forming part of the nasal cavity and orbital wall.",
  parts: [
    { name: "Cribriform Plate", type: "region", desc: "Horizontal, perforated plate through which olfactory nerve fibers (CN I) pass." },
    { name: "Crista Galli", type: "process", desc: "Triangular projection superior to the cribriform plate; attachment for the falx cerebri." },
    { name: "Perpendicular Plate", type: "region", desc: "Vertical plate forming the superior part of the nasal septum." },
    { name: "Ethmoidal Labyrinths (Lateral Masses)", type: "region", desc: "Paired lateral portions containing the ethmoidal air cells." },
    { name: "Superior Nasal Concha", type: "region", desc: "Smaller, upper curved bony shelf projecting into the nasal cavity." },
    { name: "Middle Nasal Concha", type: "region", desc: "Curved shelf projecting into the nasal cavity below the superior concha." },
    { name: "Orbital Plate (Lamina Papyracea)", type: "region", desc: "Thin plate forming most of the medial wall of the orbit." },
    { name: "Ethmoidal Sinuses (Air Cells)", type: "region", desc: "Numerous small air-filled spaces within the lateral masses." },
  ],
},

/* ================= SKULL — FACIAL BONES ================= */
{
  id: "maxilla", name: "Maxilla (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "Forms the upper jaw, hard palate, and parts of the orbit and nasal cavity.",
  parts: [
    { name: "Body", type: "region", desc: "Main hollow portion containing the maxillary sinus." },
    { name: "Frontal Process", type: "process", desc: "Projects up to articulate with the frontal bone." },
    { name: "Zygomatic Process", type: "process", desc: "Projects laterally to articulate with the zygomatic bone." },
    { name: "Alveolar Process", type: "process", desc: "Inferior ridge containing the tooth sockets (alveoli)." },
    { name: "Palatine Process", type: "process", desc: "Horizontal projection forming most of the hard palate." },
    { name: "Infraorbital Foramen", type: "foramen", desc: "Opening below the orbit for the infraorbital nerve and vessels." },
    { name: "Infraorbital Groove/Canal", type: "foramen", desc: "Channel along the orbital floor leading to the infraorbital foramen." },
    { name: "Maxillary Sinus", type: "region", desc: "Large air-filled cavity within the body, largest of the paranasal sinuses." },
    { name: "Incisive Fossa", type: "fossa", desc: "Depression on the palatine process behind the incisors; leads to incisive foramen." },
    { name: "Anterior Nasal Spine", type: "process", desc: "Sharp midline projection at the base of the nasal aperture." },
  ],
},
{
  id: "zygomatic", name: "Zygomatic Bone (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "The 'cheekbone'; forms the prominence of the cheek and part of the orbit.",
  parts: [
    { name: "Temporal Process", type: "process", desc: "Projects posteriorly to join the temporal bone's zygomatic process, forming the zygomatic arch." },
    { name: "Frontal Process", type: "process", desc: "Projects superiorly to articulate with the frontal bone." },
    { name: "Zygomaticofacial Foramen", type: "foramen", desc: "Small opening on the facial surface for a cutaneous nerve." },
    { name: "Zygomaticotemporal Foramen", type: "foramen", desc: "Opening on the temporal surface for a nerve branch." },
  ],
},
{
  id: "nasal", name: "Nasal Bone (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "Small paired bones forming the bridge of the nose.",
  parts: [
    { name: "Body", type: "region", desc: "Thin, rectangular plate forming the bony bridge of the nose." },
  ],
},
{
  id: "lacrimal", name: "Lacrimal Bone (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "Smallest bone of the face; forms part of the medial orbital wall.",
  parts: [
    { name: "Lacrimal Fossa", type: "fossa", desc: "Depression housing the lacrimal sac, which drains tears into the nasal cavity." },
  ],
},
{
  id: "palatine", name: "Palatine Bone (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "L-shaped bone forming the posterior hard palate and part of the nasal cavity/orbit.",
  parts: [
    { name: "Horizontal Plate", type: "region", desc: "Forms the posterior fifth of the hard palate." },
    { name: "Perpendicular Plate", type: "region", desc: "Forms part of the lateral nasal wall." },
    { name: "Greater Palatine Foramen", type: "foramen", desc: "Opening for the greater palatine nerve and vessels." },
  ],
},
{
  id: "inferior-concha", name: "Inferior Nasal Concha (paired)", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "An independent bone forming the largest, lowest curved shelf in the nasal cavity.",
  parts: [
    { name: "Body", type: "region", desc: "Thin, curved bony scroll projecting from the lateral nasal wall." },
  ],
},
{
  id: "vomer", name: "Vomer", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "Thin, flat bone forming the inferior/posterior nasal septum.",
  parts: [
    { name: "Body/Ala", type: "region", desc: "Plow-shaped bone forming the inferior part of the nasal septum." },
  ],
},
{
  id: "mandible", name: "Mandible", region: "Axial Skeleton", group: "Skull – Facial Bones",
  blurb: "The lower jaw; the only freely movable bone of the skull.",
  parts: [
    { name: "Body", type: "region", desc: "Horizontal, horseshoe-shaped anterior portion." },
    { name: "Ramus", type: "region", desc: "Vertical posterior portion on each side." },
    { name: "Angle (Gonial Angle)", type: "region", desc: "Point where the body meets the ramus." },
    { name: "Condylar Process (Head + Neck)", type: "condyle", desc: "Articulates with the temporal bone's mandibular fossa (TMJ)." },
    { name: "Coronoid Process", type: "process", desc: "Anterior, flat projection of the ramus for temporalis muscle attachment." },
    { name: "Mandibular Notch", type: "notch", desc: "Concave gap between the condylar and coronoid processes." },
    { name: "Mandibular Foramen", type: "foramen", desc: "Opening on the medial ramus for the inferior alveolar nerve." },
    { name: "Mental Foramen", type: "foramen", desc: "Opening on the body below the premolars for the mental nerve." },
    { name: "Mental Protuberance", type: "tuberosity", desc: "Triangular prominence forming the chin." },
    { name: "Alveolar Process", type: "process", desc: "Superior ridge containing the lower tooth sockets." },
    { name: "Mylohyoid Line", type: "crest", desc: "Ridge on the internal surface for mylohyoid muscle attachment." },
    { name: "Genial Tubercles (Mental Spines)", type: "tuberosity", desc: "Small bumps on the internal midline for genioglossus/geniohyoid attachment." },
    { name: "Lingula", type: "process", desc: "Small tongue-shaped flap of bone next to the mandibular foramen; sphenomandibular ligament attachment." },
  ],
},

/* ================= SKULL — SUTURES ================= */
{
  id: "sutures", name: "Cranial Sutures", region: "Axial Skeleton", group: "Skull – Sutures",
  blurb: "Immovable fibrous joints uniting the bones of the skull.",
  parts: [
    { name: "Coronal Suture", type: "suture", desc: "Joins the frontal bone to the two parietal bones." },
    { name: "Sagittal Suture", type: "suture", desc: "Joins the two parietal bones at the midline of the skull roof." },
    { name: "Lambdoid Suture", type: "suture", desc: "Joins the parietal bones to the occipital bone." },
    { name: "Squamous Suture", type: "suture", desc: "Joins the parietal bone to the temporal bone on each side." },
    { name: "Metopic (Frontal) Suture", type: "suture", desc: "Midline suture between the two halves of the frontal bone; usually fuses in early childhood." },
    { name: "Frontonasal Suture", type: "suture", desc: "Joins the frontal bone to the nasal bones." },
    { name: "Foramen Lacerum", type: "foramen", desc: "Junction of the sphenoid, temporal, and occipital bones at the cranial base; mostly filled with cartilage in life." },
  ],
},

/* ================= HYOID ================= */
{
  id: "hyoid", name: "Hyoid Bone", region: "Axial Skeleton", group: "Hyoid Bone",
  blurb: "U-shaped bone in the neck that does not articulate with any other bone; suspended by ligaments/muscles.",
  parts: [
    { name: "Body", type: "region", desc: "Central portion of the U-shape." },
    { name: "Greater Horns (Cornua)", type: "process", desc: "Paired posterior-projecting horns; major muscle attachment sites." },
    { name: "Lesser Horns (Cornua)", type: "process", desc: "Small paired projections near the junction of body and greater horns." },
  ],
},

/* ================= VERTEBRAL COLUMN ================= */
{
  id: "vertebra-general", name: "Generic Vertebra (Typical)", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "The basic template shared by cervical, thoracic, and lumbar vertebrae.",
  parts: [
    { name: "Body", type: "region", desc: "Anterior, weight-bearing, disc-shaped portion." },
    { name: "Vertebral Arch", type: "region", desc: "Posterior bony ring formed by pedicles and laminae." },
    { name: "Pedicles", type: "region", desc: "Two short bony processes connecting the body to the arch." },
    { name: "Laminae", type: "region", desc: "Flat plates joining the pedicles to the spinous process." },
    { name: "Spinous Process", type: "process", desc: "Posterior midline projection, often palpable through skin." },
    { name: "Transverse Processes", type: "process", desc: "Paired lateral projections for muscle/ligament attachment (and rib articulation in thoracic)." },
    { name: "Superior Articular Processes", type: "process", desc: "Face upward to articulate with the vertebra above." },
    { name: "Inferior Articular Processes", type: "process", desc: "Face downward to articulate with the vertebra below." },
    { name: "Vertebral Foramen", type: "foramen", desc: "Central opening through which the spinal cord passes." },
    { name: "Intervertebral Foramen", type: "foramen", desc: "Lateral opening between adjacent vertebrae for spinal nerve exit." },
    { name: "Superior/Inferior Vertebral Notches", type: "notch", desc: "Concavities on the pedicle margins that, stacked together, form the intervertebral foramen." },
    { name: "Facet (Zygapophyseal) Joints", type: "condyle", desc: "Paired synovial joints between the superior and inferior articular processes of adjacent vertebrae." },
  ],
},
{
  id: "cervical", name: "Cervical Vertebrae (C1–C7)", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "Seven neck vertebrae; smallest bodies, each with a transverse foramen. C1 and C2 are highly specialized.",
  parts: [
    { name: "Transverse Foramen", type: "foramen", desc: "Opening in each transverse process (unique to cervical); transmits vertebral artery/vein." },
    { name: "Bifid Spinous Process", type: "process", desc: "Split tip of the spinous process seen in C2–C6." },
    { name: "Atlas (C1) – Anterior Arch", type: "region", desc: "Front bony arch of the ring-shaped atlas; articulates with the dens." },
    { name: "Atlas (C1) – Posterior Arch", type: "region", desc: "Rear bony arch of the atlas." },
    { name: "Atlas (C1) – Lateral Masses", type: "region", desc: "Thickened sides bearing superior articular facets for the occipital condyles." },
    { name: "Atlas (C1) – Superior Articular Facets", type: "condyle", desc: "Concave surfaces that articulate with the occipital condyles ('yes' movement)." },
    { name: "Groove for Vertebral Artery", type: "crest", desc: "Groove on the posterior arch of the atlas where the vertebral artery curves toward the foramen magnum." },
    { name: "Anterior/Posterior Tubercles (Transverse Processes)", type: "tuberosity", desc: "Small bumps at the tip of a cervical transverse process, on either side of the transverse foramen." },
    { name: "Axis (C2) – Dens (Odontoid Process)", type: "process", desc: "Tooth-like peg projecting up from the body; pivot for the atlas ('no' movement)." },
    { name: "Vertebra Prominens (C7)", type: "process", desc: "Long, non-bifid spinous process of C7, easily palpable at the base of the neck." },
  ],
},
{
  id: "thoracic", name: "Thoracic Vertebrae (T1–T12)", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "Twelve vertebrae that articulate with the ribs; heart-shaped bodies, long spinous processes.",
  parts: [
    { name: "Costal Facets (Demifacets) on Body", type: "condyle", desc: "Small facets on the vertebral body for articulation with rib heads." },
    { name: "Transverse Costal Facets", type: "condyle", desc: "Facets on the transverse processes (T1–T10) for rib tubercles." },
    { name: "Long Spinous Process", type: "process", desc: "Sharply angled, downward-pointing spinous process." },
  ],
},
{
  id: "lumbar", name: "Lumbar Vertebrae (L1–L5)", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "Five large vertebrae bearing most body weight; no costal facets or transverse foramina.",
  parts: [
    { name: "Massive Body", type: "region", desc: "Large, kidney-shaped body adapted for weight bearing." },
    { name: "Short, Blunt Spinous Process", type: "process", desc: "Thick, rectangular, horizontally directed spinous process." },
  ],
},
{
  id: "sacrum", name: "Sacrum", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "Triangular bone formed by fusion of 5 sacral vertebrae; connects the spine to the pelvis.",
  parts: [
    { name: "Base", type: "region", desc: "Broad superior surface articulating with L5." },
    { name: "Sacral Promontory", type: "region", desc: "Anterior projecting edge of the base; obstetric landmark." },
    { name: "Ala (Wing)", type: "region", desc: "Winged lateral surface on each side of the base." },
    { name: "Median Sacral Crest", type: "crest", desc: "Midline ridge formed by fused spinous processes." },
    { name: "Anterior Sacral Foramina", type: "foramen", desc: "Four paired openings on the pelvic surface for ventral rami." },
    { name: "Posterior Sacral Foramina", type: "foramen", desc: "Four paired openings on the dorsal surface for dorsal rami." },
    { name: "Sacral Canal", type: "foramen", desc: "Continuation of the vertebral canal within the sacrum." },
    { name: "Sacral Hiatus", type: "notch", desc: "Inferior opening of the sacral canal (site of caudal epidural injections)." },
    { name: "Auricular Surface", type: "condyle", desc: "Ear-shaped surface articulating with the ilium (sacroiliac joint)." },
    { name: "Apex", type: "region", desc: "Inferior tip articulating with the coccyx." },
    { name: "Sacral Cornua", type: "process", desc: "Small paired horns flanking the sacral hiatus, articulating with the coccygeal cornua." },
  ],
},
{
  id: "coccyx", name: "Coccyx", region: "Axial Skeleton", group: "Vertebral Column",
  blurb: "The 'tailbone'; formed by fusion of 3–5 rudimentary coccygeal vertebrae.",
  parts: [
    { name: "Coccygeal Cornua", type: "process", desc: "Small horns projecting up to articulate with the sacral cornua." },
  ],
},

/* ================= THORACIC CAGE ================= */
{
  id: "sternum", name: "Sternum", region: "Axial Skeleton", group: "Thoracic Cage",
  blurb: "Flat, dagger-shaped bone in the anterior midline of the thorax.",
  parts: [
    { name: "Manubrium", type: "region", desc: "Superior, trapezoid-shaped segment." },
    { name: "Jugular (Suprasternal) Notch", type: "notch", desc: "Concave upper border of the manubrium, palpable between the clavicles." },
    { name: "Clavicular Notch", type: "notch", desc: "Facet on the manubrium articulating with the clavicle." },
    { name: "Sternal Angle", type: "region", desc: "Junction of manubrium and body; landmark for the 2nd rib/costal cartilage." },
    { name: "Body (Corpus Sterni)", type: "region", desc: "Long middle portion; articulates with costal cartilages of ribs 2–7." },
    { name: "Xiphoid Process", type: "process", desc: "Smallest, inferior-most, often cartilaginous segment." },
  ],
},
{
  id: "ribs", name: "Ribs (12 pairs)", region: "Axial Skeleton", group: "Thoracic Cage",
  blurb: "Curved bones forming the thoracic cage; classified as true (1–7), false (8–10), and floating (11–12).",
  parts: [
    { name: "Head", type: "region", desc: "Posterior end bearing facets that articulate with vertebral bodies." },
    { name: "Neck", type: "region", desc: "Constricted region between head and tubercle." },
    { name: "Tubercle", type: "tuberosity", desc: "Bump near the neck articulating with the transverse process of a thoracic vertebra." },
    { name: "Shaft (Body)", type: "region", desc: "Long, thin, curved main portion of the rib." },
    { name: "Angle of Rib", type: "region", desc: "Point of sharpest curvature along the shaft, just lateral to the tubercle." },
    { name: "Costal Groove", type: "crest", desc: "Groove on the inferior internal surface sheltering intercostal vessels/nerve." },
    { name: "Costal Cartilage", type: "region", desc: "Hyaline cartilage connecting the rib to the sternum (true ribs) or rib above (false ribs)." },
    { name: "True Ribs (1–7)", type: "region", desc: "Attach directly to the sternum via their own costal cartilage." },
    { name: "False Ribs (8–10)", type: "region", desc: "Cartilage attaches to the cartilage of the rib above rather than the sternum." },
    { name: "Floating Ribs (11–12)", type: "region", desc: "Have no anterior attachment at all." },
  ],
},

/* ================= PECTORAL GIRDLE ================= */
{
  id: "clavicle", name: "Clavicle", region: "Appendicular Skeleton", group: "Pectoral Girdle",
  blurb: "S-shaped 'collarbone' connecting the arm to the trunk; the only long bone that ossifies by intramembranous ossification.",
  parts: [
    { name: "Sternal End", type: "region", desc: "Rounded medial end articulating with the sternal manubrium." },
    { name: "Acromial End", type: "region", desc: "Flattened lateral end articulating with the scapula's acromion." },
    { name: "Conoid Tubercle", type: "tuberosity", desc: "Projection on the inferior surface for the conoid ligament." },
    { name: "Shaft", type: "region", desc: "Curved middle portion of the bone." },
  ],
},
{
  id: "scapula", name: "Scapula", region: "Appendicular Skeleton", group: "Pectoral Girdle",
  blurb: "Triangular 'shoulder blade' lying on the posterior rib cage.",
  parts: [
    { name: "Body", type: "region", desc: "Thin, triangular flat plate." },
    { name: "Spine", type: "crest", desc: "Prominent diagonal ridge on the posterior surface." },
    { name: "Acromion", type: "process", desc: "Lateral extension of the spine; articulates with the clavicle." },
    { name: "Coracoid Process", type: "process", desc: "Anterior, hook-like projection for muscle/ligament attachment." },
    { name: "Glenoid Cavity (Fossa)", type: "fossa", desc: "Shallow socket that articulates with the humeral head (shoulder joint)." },
    { name: "Supraspinous Fossa", type: "fossa", desc: "Depression above the spine housing supraspinatus." },
    { name: "Infraspinous Fossa", type: "fossa", desc: "Larger depression below the spine housing infraspinatus." },
    { name: "Subscapular Fossa", type: "fossa", desc: "Shallow concavity on the anterior (costal) surface housing subscapularis." },
    { name: "Superior Border", type: "region", desc: "Shortest, sharpest superior edge." },
    { name: "Medial (Vertebral) Border", type: "region", desc: "Edge closest to the vertebral column." },
    { name: "Lateral (Axillary) Border", type: "region", desc: "Thick edge closest to the axilla." },
    { name: "Superior Angle", type: "region", desc: "Angle where superior and medial borders meet." },
    { name: "Inferior Angle", type: "region", desc: "Angle where medial and lateral borders meet; rotates during arm abduction." },
    { name: "Suprascapular Notch", type: "notch", desc: "Notch on the superior border for the suprascapular nerve." },
    { name: "Supraglenoid Tubercle", type: "tuberosity", desc: "Small bump above the glenoid cavity; origin of the long head of biceps brachii." },
    { name: "Infraglenoid Tubercle", type: "tuberosity", desc: "Roughening below the glenoid cavity; origin of the long head of triceps brachii." },
    { name: "Spinoglenoid Notch", type: "notch", desc: "Notch between the scapular spine and glenoid rim for the suprascapular nerve/vessels." },
  ],
},

/* ================= UPPER LIMB ================= */
{
  id: "humerus", name: "Humerus", region: "Appendicular Skeleton", group: "Upper Limb",
  blurb: "The single long bone of the arm (between shoulder and elbow).",
  parts: [
    { name: "Head", type: "region", desc: "Smooth, rounded proximal surface articulating with the glenoid cavity." },
    { name: "Anatomical Neck", type: "region", desc: "Slight constriction just below the head." },
    { name: "Surgical Neck", type: "region", desc: "Narrowed region below the tubercles; common fracture site." },
    { name: "Greater Tubercle", type: "tuberosity", desc: "Lateral bony projection; attachment for rotator cuff muscles." },
    { name: "Lesser Tubercle", type: "tuberosity", desc: "Anterior bony projection; attachment for subscapularis." },
    { name: "Intertubercular (Bicipital) Groove", type: "crest", desc: "Groove between the tubercles housing the long head of biceps tendon." },
    { name: "Deltoid Tuberosity", type: "tuberosity", desc: "V-shaped roughening on the lateral shaft for deltoid attachment." },
    { name: "Radial (Spiral) Groove", type: "crest", desc: "Diagonal groove on the posterior shaft for the radial nerve." },
    { name: "Capitulum", type: "condyle", desc: "Rounded lateral condyle articulating with the radial head." },
    { name: "Trochlea", type: "condyle", desc: "Pulley-shaped medial condyle articulating with the ulna." },
    { name: "Medial Epicondyle", type: "condyle", desc: "Prominent medial projection; site of the 'funny bone' (ulnar nerve)." },
    { name: "Lateral Epicondyle", type: "condyle", desc: "Smaller lateral projection for forearm extensor origin." },
    { name: "Coronoid Fossa", type: "fossa", desc: "Anterior depression that receives the ulnar coronoid process in flexion." },
    { name: "Radial Fossa", type: "fossa", desc: "Small anterior depression receiving the radial head in flexion." },
    { name: "Olecranon Fossa", type: "fossa", desc: "Posterior depression receiving the olecranon in extension." },
    { name: "Crest of Greater Tubercle", type: "crest", desc: "Ridge descending from the greater tubercle forming the lateral lip of the intertubercular groove." },
    { name: "Crest of Lesser Tubercle", type: "crest", desc: "Ridge descending from the lesser tubercle forming the medial lip of the intertubercular groove." },
  ],
},
{
  id: "radius", name: "Radius", region: "Appendicular Skeleton", group: "Upper Limb",
  blurb: "Lateral (thumb-side) forearm bone.",
  parts: [
    { name: "Head", type: "region", desc: "Disc-shaped proximal end articulating with the humeral capitulum and ulna." },
    { name: "Neck", type: "region", desc: "Constricted region just below the head." },
    { name: "Radial Tuberosity", type: "tuberosity", desc: "Roughened projection for biceps brachii tendon attachment." },
    { name: "Styloid Process", type: "process", desc: "Pointed projection at the distal lateral end." },
    { name: "Ulnar Notch", type: "notch", desc: "Concavity on the distal medial surface articulating with the ulnar head." },
    { name: "Interosseous Border", type: "crest", desc: "Sharp medial ridge of the radial shaft where the interosseous membrane (connecting radius to ulna) attaches." },
  ],
},
{
  id: "ulna", name: "Ulna", region: "Appendicular Skeleton", group: "Upper Limb",
  blurb: "Medial (pinky-side) forearm bone; main forearm bone of the elbow joint.",
  parts: [
    { name: "Olecranon Process", type: "process", desc: "Proximal projection forming the point of the elbow." },
    { name: "Coronoid Process", type: "process", desc: "Anterior projection that fits into the humeral coronoid fossa." },
    { name: "Trochlear (Semilunar) Notch", type: "notch", desc: "Large curved surface articulating with the humeral trochlea." },
    { name: "Radial Notch", type: "notch", desc: "Lateral concavity articulating with the radial head." },
    { name: "Head", type: "region", desc: "Small, rounded distal end." },
    { name: "Styloid Process", type: "process", desc: "Pointed projection on the distal posterior side." },
    { name: "Interosseous Border", type: "crest", desc: "Sharp lateral ridge of the ulnar shaft where the interosseous membrane (connecting ulna to radius) attaches." },
    { name: "Supinator Crest", type: "crest", desc: "Ridge on the proximal ulna for attachment of the supinator muscle." },
  ],
},
{
  id: "carpals", name: "Carpal Bones (8, per wrist)", region: "Appendicular Skeleton", group: "Upper Limb",
  blurb: "Eight small bones arranged in two rows forming the wrist. Mnemonic: 'Some Lovers Try Positions That They Can't Handle.'",
  parts: [
    { name: "Scaphoid", type: "region", desc: "Proximal row, lateral (thumb) side; most commonly fractured carpal." },
    { name: "Lunate", type: "region", desc: "Proximal row, moon-shaped, central." },
    { name: "Triquetrum", type: "region", desc: "Proximal row, medial side." },
    { name: "Pisiform", type: "region", desc: "Small pea-shaped sesamoid bone anterior to the triquetrum." },
    { name: "Trapezium", type: "region", desc: "Distal row, lateral (thumb) side; articulates with metacarpal I." },
    { name: "Trapezoid", type: "region", desc: "Distal row, small bone next to trapezium." },
    { name: "Capitate", type: "region", desc: "Distal row, largest carpal, central." },
    { name: "Hamate", type: "region", desc: "Distal row, medial side, with a hook-like process (Hook of Hamate)." },
    { name: "Hook of Hamate", type: "process", desc: "Curved projection forming part of the border of the carpal tunnel." },
  ],
},
{
  id: "hand-digits", name: "Metacarpals & Phalanges", region: "Appendicular Skeleton", group: "Upper Limb",
  blurb: "The bones of the palm (metacarpals I–V) and fingers (phalanges).",
  parts: [
    { name: "Metacarpals (I–V)", type: "region", desc: "Five bones forming the palm; each has a base, shaft, and head." },
    { name: "Proximal Phalanges", type: "region", desc: "First row of finger bones, closest to the palm (thumb has no middle phalanx)." },
    { name: "Middle Phalanges", type: "region", desc: "Second row of finger bones (absent in the thumb)." },
    { name: "Distal Phalanges", type: "region", desc: "Terminal finger bones." },
  ],
},

/* ================= PELVIC GIRDLE ================= */
{
  id: "hipbone", name: "Hip Bone (Os Coxae)", region: "Appendicular Skeleton", group: "Pelvic Girdle",
  blurb: "Formed by fusion of ilium, ischium, and pubis; unites with its partner and the sacrum to form the pelvis.",
  parts: [
    { name: "Iliac Crest", type: "crest", desc: "Superior curved rim of the ilium, palpable at the waistline." },
    { name: "Anterior Superior Iliac Spine (ASIS)", type: "process", desc: "Anterior end of the iliac crest; palpable hip landmark, sartorius origin." },
    { name: "Anterior Inferior Iliac Spine (AIIS)", type: "process", desc: "Projection below the ASIS; origin of rectus femoris." },
    { name: "Posterior Superior Iliac Spine (PSIS)", type: "process", desc: "Posterior end of the iliac crest; marked by a skin dimple." },
    { name: "Posterior Inferior Iliac Spine (PIIS)", type: "process", desc: "Projection below the PSIS." },
    { name: "Greater Sciatic Notch", type: "notch", desc: "Large notch inferior to the PIIS; sciatic nerve passes through this region." },
    { name: "Iliac Fossa", type: "fossa", desc: "Smooth concave surface on the internal ilium; iliacus muscle origin." },
    { name: "Auricular Surface", type: "condyle", desc: "Ear-shaped surface articulating with the sacrum (sacroiliac joint)." },
    { name: "Arcuate Line", type: "crest", desc: "Ridge marking the boundary between the false and true pelvis." },
    { name: "Ischial Spine", type: "process", desc: "Pointed projection separating the greater and lesser sciatic notches." },
    { name: "Lesser Sciatic Notch", type: "notch", desc: "Smaller notch inferior to the ischial spine." },
    { name: "Ischial Tuberosity", type: "tuberosity", desc: "Rough, thick projection that bears body weight when sitting; hamstring origin." },
    { name: "Ischial Ramus", type: "region", desc: "Bar of bone extending from the tuberosity to join the pubis." },
    { name: "Pubic Crest", type: "crest", desc: "Anterior border of the pubis." },
    { name: "Pubic Tubercle", type: "tuberosity", desc: "Small projection at the lateral end of the pubic crest; inguinal ligament attachment." },
    { name: "Pubic Symphysis (Surface)", type: "region", desc: "Roughened medial surface that meets its counterpart via a cartilaginous joint." },
    { name: "Superior Pubic Ramus", type: "region", desc: "Superior bar of the pubis extending toward the acetabulum." },
    { name: "Inferior Pubic Ramus", type: "region", desc: "Inferior bar of the pubis joining the ischial ramus." },
    { name: "Obturator Foramen", type: "foramen", desc: "Large opening formed by the ischium and pubis; mostly closed by a membrane." },
    { name: "Acetabulum", type: "fossa", desc: "Deep cup-shaped socket where ilium, ischium, and pubis meet; articulates with the femoral head." },
    { name: "Pecten Pubis (Pectineal Line)", type: "crest", desc: "Sharp ridge along the superior pubic ramus, continuous with the arcuate line; part of the pelvic brim." },
    { name: "Iliac Tuberosity", type: "tuberosity", desc: "Roughened area posterior to the auricular surface for sacroiliac ligament attachment." },
    { name: "Gluteal Lines (Ant./Post./Inf.)", type: "crest", desc: "Faint lines on the external ilium marking boundaries of gluteal muscle attachment." },
  ],
},

/* ================= LOWER LIMB ================= */
{
  id: "femur", name: "Femur", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "The thigh bone; longest, heaviest, and strongest bone in the body.",
  parts: [
    { name: "Head", type: "region", desc: "Rounded proximal end articulating with the acetabulum." },
    { name: "Fovea Capitis", type: "fossa", desc: "Small pit on the head for attachment of the ligamentum teres." },
    { name: "Neck", type: "region", desc: "Constricted region connecting the head to the shaft; common fracture site." },
    { name: "Greater Trochanter", type: "tuberosity", desc: "Large lateral projection for gluteal muscle attachment." },
    { name: "Lesser Trochanter", type: "tuberosity", desc: "Smaller medial-posterior projection for iliopsoas attachment." },
    { name: "Trochanteric Fossa", type: "fossa", desc: "Deep pit on the medial surface of the greater trochanter for obturator externus attachment." },
    { name: "Intertrochanteric Line", type: "crest", desc: "Ridge on the anterior surface connecting the two trochanters." },
    { name: "Intertrochanteric Crest", type: "crest", desc: "Ridge on the posterior surface connecting the two trochanters." },
    { name: "Gluteal Tuberosity", type: "tuberosity", desc: "Roughened ridge for gluteus maximus attachment." },
    { name: "Linea Aspera", type: "crest", desc: "Prominent longitudinal ridge on the posterior shaft for muscle attachment." },
    { name: "Medial Condyle", type: "condyle", desc: "Medial rounded distal projection articulating with the tibia." },
    { name: "Lateral Condyle", type: "condyle", desc: "Lateral rounded distal projection articulating with the tibia." },
    { name: "Medial Epicondyle", type: "condyle", desc: "Bump superior to the medial condyle for ligament attachment." },
    { name: "Lateral Epicondyle", type: "condyle", desc: "Bump superior to the lateral condyle for ligament attachment." },
    { name: "Adductor Tubercle", type: "tuberosity", desc: "Small projection above the medial epicondyle for adductor magnus attachment." },
    { name: "Patellar Surface", type: "condyle", desc: "Anterior groove between the condyles articulating with the patella." },
    { name: "Intercondylar Fossa (Notch)", type: "fossa", desc: "Deep posterior depression between the condyles for cruciate ligament attachment." },
    { name: "Pectineal Line", type: "crest", desc: "Ridge running from the lesser trochanter toward the linea aspera; pectineus attachment." },
    { name: "Quadrate Tubercle", type: "tuberosity", desc: "Small round bump on the intertrochanteric crest for quadratus femoris attachment." },
  ],
},
{
  id: "patella", name: "Patella", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "The kneecap; the largest sesamoid bone in the body, embedded in the quadriceps tendon.",
  parts: [
    { name: "Base", type: "region", desc: "Broad, flat superior border." },
    { name: "Apex", type: "region", desc: "Pointed inferior border, anchoring the patellar ligament." },
    { name: "Articular Facets", type: "condyle", desc: "Posterior surfaces articulating with the femoral condyles." },
  ],
},
{
  id: "tibia", name: "Tibia", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "The 'shin bone'; medial and weight-bearing bone of the leg.",
  parts: [
    { name: "Medial Condyle", type: "condyle", desc: "Medial proximal expansion articulating with the femur." },
    { name: "Lateral Condyle", type: "condyle", desc: "Lateral proximal expansion articulating with the femur." },
    { name: "Intercondylar Eminence", type: "process", desc: "Ridge between the condyles for cruciate ligament attachment." },
    { name: "Tibial Tuberosity", type: "tuberosity", desc: "Roughened anterior projection for patellar ligament attachment." },
    { name: "Anterior Border (Crest)", type: "crest", desc: "Sharp ridge palpable along the front of the shin." },
    { name: "Soleal Line", type: "crest", desc: "Diagonal ridge on the posterior surface for soleus muscle origin." },
    { name: "Medial Malleolus", type: "process", desc: "Distal medial projection forming the inner ankle bump." },
    { name: "Fibular Notch", type: "notch", desc: "Distal lateral concavity articulating with the fibula." },
    { name: "Interosseous Border", type: "crest", desc: "Lateral ridge of the shaft where the interosseous membrane (connecting tibia to fibula) attaches." },
    { name: "Posterior Intercondylar Area", type: "region", desc: "Flattened area behind the intercondylar eminence for ligament attachment." },
  ],
},
{
  id: "fibula", name: "Fibula", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "Thin, lateral leg bone; non-weight-bearing, mainly for muscle attachment.",
  parts: [
    { name: "Head", type: "region", desc: "Proximal expanded end articulating with the tibia (not the femur)." },
    { name: "Neck", type: "region", desc: "Constriction just below the head." },
    { name: "Lateral Malleolus", type: "process", desc: "Distal projection forming the outer ankle bump." },
  ],
},
{
  id: "tarsals", name: "Tarsal Bones (7, per foot)", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "Seven bones forming the posterior foot (ankle region), analogous to the carpals.",
  parts: [
    { name: "Talus", type: "region", desc: "Uppermost tarsal; articulates with the tibia and fibula at the ankle joint." },
    { name: "Talar Head", type: "region", desc: "Rounded anterior portion of the talus articulating with the navicular." },
    { name: "Talar Neck", type: "region", desc: "Constricted region between the talar body and head." },
    { name: "Calcaneus", type: "region", desc: "Largest tarsal, forms the heel." },
    { name: "Sinus Tarsi", type: "fossa", desc: "Cone-shaped canal/depression between the talus and calcaneus, felt as a soft spot in front of the lateral malleolus." },
    { name: "Sustentaculum Tali", type: "process", desc: "Shelf-like projection of the calcaneus supporting the talus." },
    { name: "Calcaneal Tuberosity", type: "tuberosity", desc: "Posterior projection of the calcaneus; Achilles tendon attachment." },
    { name: "Navicular", type: "region", desc: "Boat-shaped bone medial to the cuboid, anterior to the talus." },
    { name: "Cuboid", type: "region", desc: "Lateral tarsal, anterior to the calcaneus." },
    { name: "Medial Cuneiform", type: "region", desc: "Medial one of three cuneiforms, anterior to the navicular." },
    { name: "Intermediate Cuneiform", type: "region", desc: "Middle cuneiform bone." },
    { name: "Lateral Cuneiform", type: "region", desc: "Lateral cuneiform bone, adjacent to the cuboid." },
  ],
},
{
  id: "foot-digits", name: "Metatarsals & Phalanges", region: "Appendicular Skeleton", group: "Lower Limb",
  blurb: "The bones of the sole (metatarsals I–V) and toes (phalanges).",
  parts: [
    { name: "Metatarsals (I–V)", type: "region", desc: "Five bones forming the sole, each with a base, shaft, and head." },
    { name: "Proximal Phalanges", type: "region", desc: "First row of toe bones." },
    { name: "Middle Phalanges", type: "region", desc: "Second row of toe bones (absent in the great toe)." },
    { name: "Distal Phalanges", type: "region", desc: "Terminal toe bones." },
  ],
},
];

/* Flatten into a single searchable/quizzable list of {bone, name, type, desc, group, region} */
const ALL_PARTS = BONES.flatMap(b =>
  b.parts.map(p => ({ ...p, bone: b.name, boneId: b.id, group: b.group, region: b.region }))
);
